version: '2'
services:

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/wp-content/plugins/cl-typograf
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress